### PR TITLE
Add the "client_credentials" grant type to the default admin client

### PR DESCRIPTION
**Pull request by pletessier**
See issue https://github.com/gravitee-io/issues/issues/1281

### CODE REVIEW

**Comment by tcompiegne** [comment]
Hi @pletessier, don't you think we should also update existing admin client ?

Your code only apply if the admin client doesn't exist.

**Comment by pletessier** [comment]
Hi @tcompiegne ,
From my point of view, setting the grant_type at init is enough. I just need that to be able to create an access_token the first time. If user changes are made after, I suppose that Gravitee shouldn't overwrite them. It would be confusing.

**Comment by tcompiegne** [comment]
All right, according to our contributing guide, can you sign the [CLA](https://download.gravitee.io/cla.pdf), and I will accept your PR.

```
Contributor License Agreement

Please sign our Contributor License Agreement (CLA) and send it to contact@graviteesource.com. For any code changes to be accepted, the CLA must be signed.
```

Thanks.
Regards.

**Comment by tcompiegne** [comment]
👍

**Pull request merged**
